[versions]
activity = "1.7.2"
agp = "8.2.0-alpha16"
androidx-test-ext-junit = "1.1.5"
browser = "1.6.0"
core = "1.10.1"
crashlytics = "2.9.8"
espresso-core = "3.5.1"
firebase = "32.2.2"
junit = "4.13.2"
kotlin = "1.9.0"
lifecycle = "2.6.1"
google-services = "4.3.15"
play-services-location = "21.0.1"
timber = "5.0.1"
versions = "0.47.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "lifecycle" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
